name: Build Passy for all platforms
on:
  workflow_dispatch
jobs:
  build_linux:
    name: Build Passy for Android and Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        shell: bash
        run: sudo apt-get -y install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev binutils coreutils desktop-file-utils fakeroot fuse libgdk-pixbuf2.0-dev patchelf python3-pip python3-setuptools squashfs-tools strace util-linux zsync
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.4'
          channel: 'stable'
      - name: Configure flutter
        shell: bash
        run: flutter config --no-analytics
      - name: Build with updates popup
        shell: bash
        run: bash build_all_with_updates_popup.sh
      - name: Upload Android build
        uses: actions/upload-artifact@v3
        with:
          name: android
          path: /home/runner/work/Passy/Passy/build/app/outputs/flutter-apk/app-release.apk
      - name: Upload Linux bundle build
        uses: actions/upload-artifact@v3
        with:
          name: linux-bundle
          path: /home/runner/work/Passy/Passy/build/linux/x64/release/bundle
      - name: Upload Linux AppImage build
        uses: actions/upload-artifact@v3
        with:
          name: linux-appimage
          path: /home/runner/work/Passy/Passy/build/appimage/Passy-Latest-x86_64.AppImage
      - name: Build without updates popup
        shell: bash
        run: bash build_all_without_updates_popup.sh
      - name: Upload Linux bundle no updates popup build
        uses: actions/upload-artifact@v3
        with:
          name: linux-bundle-no-updates-popup
          path: /home/runner/work/Passy/Passy/build/linux/x64/release/bundle
      - name: Upload Linux AppImage no updates popup build
        uses: actions/upload-artifact@v3
        with:
          name: linux-appimage-no-updates-popup
          path: /home/runner/work/Passy/Passy/build/appimage/Passy-Latest-x86_64.AppImage
      - name: Upload Android no updates popup build
        uses: actions/upload-artifact@v3
        with:
          name: android-no-updates-popup
          path: /home/runner/work/Passy/Passy/build/app/outputs/flutter-apk/app-release.apk
  build_windows:
    name: Build Passy for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.4'
          channel: 'stable'
      - name: Configure flutter
        shell: bash
        run: flutter config --no-analytics
      - name: Build Passy for Windows
        shell: bash
        run: ./build_windows_with_updates_popup.bat
      - name: Upload Windows portable build
        uses: actions/upload-artifact@v3
        with:
          name: windows-portable
          path: build/windows
